var localeJSON = JSON.flatten({
  "calendar" : {
    "title" : {
      "fi" : "Yhteishaut ja hakulomakkeet",
      "sv" : "Kommande ansökningar",
      "en" : "Joint applications and application forms"
    }
  },
  "frontpage" : {
    "image" : {
      "fi" : "<h2>Peruskoulun jälkeen?</h2><img src='/app/img/demo/Peruskoululaiset-2-390x260.jpg' style='max-width:100%' class='attachment-oph-intro wp-post-image' alt='Kolme tyttöä seisoo ulkona puiden edessä. Kuva: Olli Häkämies'><p></p><h4>Minne hakisin?</h4><ul class='list-unstyled'> <li><a class='no_icon' title='Käynnistä ohjaava koulutushaku' href='/app/#!/hakuwizard?phase=phaseone&amp;phaseone=pk'>Olen käynyt peruskoulun</a></li></ul>",
      "sv" : "<h2>Efter grundskolan?</h2><img src='/app/img/demo/Peruskoululaiset-2-390x260.jpg' style='max-width:100%' class='attachment-oph-intro wp-post-image' alt='Kolme tyttöä seisoo ulkona puiden edessä. Kuva: Olli Häkämies'><p></p><h4>Vart ska jag söka?</h4><ul class='list-unstyled'> <li><a class='no_icon' href='/app/#!/hakuwizard?phase=phaseone&amp;phaseone=pk'>Jag har gått grundskolan</a></li></ul>"
    },
      "info" : {
          "fi" : "<h1>Tervetuloa Opintopolku.fi- palvelun Demoon</h1><p>Demossa voit tutustua kevään 2020 hakujen koulutuksiin ja täyttää harjoitushakulomakkeen. <p><strong>Muistathan, että demossa lähettämäsi lomake ei ole oikea hakulomake.</strong> Demo ei ole käytössä hakuaikoina eikä hakuaikoja edeltävinä päivinä. Keväällä haetaan syksyllä 2020 alkaviin koulutuksiin. HUOM! Muutokset Demon koulutustarjontaan ovat mahdollisia.</p><p><strong>Demossa voit harjoitella hakemista seuraavissa hauissa:</strong></p><h2><strong> Ammatillisen koulutuksen ja lukiokoulutuksen yhteishaku</strong></h2><p>Ammatillisen koulutuksen ja lukiokoulutuksen yhteishaussa voit hakea ammatilliseen perustutkintoon sekä lukioon. Ammatillisessa koulutuksessa on tarjolla sekä peruskoulupohjaisia että lukiopohjaisia koulutuksia.</p><h2><strong>Haku vaativan erityisen tuen perusteella järjestettävään ammatilliseen koulutukseen</strong></h2><p>Vaativan erityisen tuen perusteella järjestettävän ammatillisen koulutuksen haussa voit hakea vaativan erityisen tuen perusteella järjestettäviin  ammatillisiin perustutkintoihin, ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) sekä työhön ja itsenäiseen elämään valmentavaan koulutukseen (TELMA). </p><h2>Perusopetuksen jälkeisen valmistavan koulutuksen haku</h2><p>Perusopetuksen jälkeisen valmistavan koulutuksen haussa voit hakea kymppiluokille, ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) sekä maahanmuuttajille ja vieraskielisille tarkoitettuun lukiokoulutukseen valmistavaan koulutukseen (LUVA). <p><a href='https://opintopolku.fi' target='_blank'>Lue lisää hakemisesta ja valintaperusteista Opintopolku.fi-sivustolta</a></p><hr>",
          "sv" : "<h1>Välkommen till Demoversionen av Studieinfo.fi</h1><p>Här kan du bekanta dig med utbildningar som ingår i ansökningar under våren 2020. Du kan dessutom fylla i en övningsansökningsblankett. <p><strong>Kom ihåg att en blankett som du skickar i demoversionen inte är en riktig ansökan. </strong>Demoversionen är inte i bruk under ansökningstiderna eller under de närmast föregående dagarna före ansökningstiderna. I vårens ansökan söker du till utbildningar som börjar på hösten 2020. OBS! Det kan uppstå vissa ändringar i fråga om utbildningarna i demoversionen. </p><p><strong>I demoversionen kan du öva dig i att söka till utbildningar som ingår i följande ansökningar:</p></strong><p><h2>Gemensam ansökan till yrkes- och gymnasieutbildning</h2><p>I den gemensamma ansökan kan du söka till yrkesinriktade grundexamina och till gymnasium.</p><p><h2>Ansökan till yrkesutbildning med krävande särskilt stöd</h2></p>I ansökan till yrkesutbildning med krävande särskilt stöd kan du söka till yrkesinriktade grundexamina och utbildning som handleder för yrkesutbildning (VALMA), vilka ordnas med särskilt krävande stöd och till utbildning som handleder för arbete och ett självständigt liv (TELMA). </p><p><h2>Ansökan till handledande utbildningar efter grundläggande utbildning </h2></p>I ansökan till handledande utbildningar efter grundläggande utbildning kan du söka till tionde klasser, utbildning som handleder för yrkesutbildning (VALMA) och utbildning som förbereder invandrare och andra personer med ett främmande språk för gymnasium (LUVA). </p><p>Läs mera om ansökan och antagning på <a href='http://www.studieinfo.fi' class='external' target='_blank'>www.studieinfo.fi</a></p><hr>"
      },
    "ohje-button" : {
      "fi" : "Tutustu ohjeisiin: Näin haet demohaussa",
      "sv" : "Bekanta dig med anvisningarna: Så här söker du i demo-ansökan"
    }
  },
  "demoohje" : {
    "text" : {
      "fi" : "<h1>Tervetuloa Opintopolku.fi- palvelun Demoon</h1><p>Täällä voit tutustua kevään 2020 hakujen koulutuksiin ja täyttää harjoitushakulomakkeen. Demossa voit harjoitella hakemista:</p><ul><li>ammatilliseen koulutukseen tai lukioon</li><li>vaativan erityisen tuen perusteella järjestettävään ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) tai työhön ja itsenäiseen elämään valmentavaan koulutukseen (TELMA)</li><li>kymppiluokalle, ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) tai maahanmuuttajille ja vieraskielisille tarkoitettuun lukiokoulutukseen valmistavaan koulutukseen (LUVA)</li></ul><p><strong>Muistathan, että demossa lähettämäsi lomake ei ole oikea hakulomake.</strong> Jos haluat käyttää ruotsinkielistä versiota, vaihda käyttöliittymäkieli ruotsiksi sivun oikeasta ylälaidasta. Demo ei ole käytössä hakuaikoina eikä hakuaikoja edeltävinä päivinä. HUOM! Muutokset Demon koulutustarjontaan ovat mahdollisia. Löydät demosta koulutukset alla mainittuihin hakuihin:</p> <h2><strong>Kevään 2020 ammatillisen koulutuksen ja lukiokoulutuksen yhteishaku</strong></h2><p>Ammatillisen koulutuksen ja lukiokoulutuksen yhteishaussa <strong>18.2.–10.3.2020</strong> voit hakea ammatilliseen perustutkintoon johtavaan koulutukseen sekä lukioon. Keväällä haetaan syksyllä 2020 alkaviin koulutuksiin. Ammatillisessa koulutuksessa on tarjolla sekä peruskoulupohjaisia että lukiopohjaisia koulutuksia.</p><h2><strong>Kevään 2020 haku vaativan erityisen tuen perusteella järjestettävään ammatilliseen koulutukseen haku</strong></h2><p>Vaativan erityisen tuen perusteella järjestettävän ammatillisen koulutuksen haussa <strong>11.3.–1.4.2020</strong> voit hakea vaativan erityisen tuen perusteella järjestettäviin  ammatillisiin perustutkintoihin, ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) sekä työhön ja itsenäiseen elämään valmentavaan koulutukseen (TELMA). Keväällä haetaan syksyllä 2020 alkaviin koulutuksiin.</p><h2>Kevään 2020 perusopetuksen jälkeisen valmistavan koulutuksen haku</h2><p>Perusopetuksen jälkeisen valmistavan koulutuksen haussa <strong>19.5.–21.7.2020</strong> voit hakea kymppiluokille, ammatilliseen koulutukseen valmentavaan koulutukseen (VALMA) sekä maahanmuuttajille ja vieraskielisille tarkoitettuun lukiokoulutukseen valmistavaan koulutukseen (LUVA). Keväällä haetaan syksyllä 2020 alkaviin koulutuksiin.</p><p>Lue lisää hakemisesta ja valintaperusteista <a href='https://opintopolku.fi' target='_blank'>Opintopolku.fi-</a>sivustolta.</p><hr>",
      "sv" : "<h1>Välkommen till Demoversionen av Studieinfo.fi</h1><p>I demoversionen kan du bekanta dig med utbildningar som ingår i olika ansökningar under våren 2019. Du kan dessutom fylla i en övningsansökningsblankett. I demon kan du öva dig på att söka till:</p><ul><li>Yrkesutbildning eller gymnasium</li><li>yrkesinriktade grundexamina, handledande utbildning för yrkesutbildning (VALMA), som ordnas med särskilt krävande stöd och till utbildning som handleder för arbete och ett självständigt liv (TELMA).</li><li>Tionde klassen, utbildning som handleder för yrkesutbildning (VALMA) eller utbildning som förbereder invandrare för gymnasieutbildning (LUVA)</li></ul><p><strong>Kom ihåg att en blankett som du skickar i demoversionen inte är en riktig ansökan.</strong> Om du vill kan du ändra demoversionens språk till finska i övre kanten av sidan.</p><p>Demoversionen är inte i bruk under ansökningstiderna och inte heller under de närmast föregående dagarna före ansökningstiderna.</p><p>OBS! Det kan uppstå vissa ändringar i fråga om utbildningarna i demoversionen. I demoversionen hittar du utbildningar som ingår i följande ansökningar:</p><h2><strong>Gemensam ansökan till yrkes- och gymnasieutbildning våren 2019</strong></h2><p>I den gemensamma ansökan till yrkes- och gymnasieutbildning som ordnas <strong>19.2.–12.3.2019</strong>, kan du söka till yrkesinriktade grundexamina och till gymnasium. I vårens ansökan söker du till utbildningar som börjar på hösten 2019. Inom yrkesutbildning finns både grundskole- och gymnasiebaserade utbildningar.</p><h2><strong>Ansökan våren 2019 till yrkesutbildning med särskilt krävande stöd</strong></h2><p>I ansökan till yrkesutbildning med särskilt krävande stöd <strong>13.3.–3.4.2019</strong> kan du söka till yrkesinriktade grundexamina, handledande utbildning för yrkesutbildning (VALMA), som ordnas med särskilt krävande stöd och till utbildning som handleder för arbete och ett självständigt liv (TELMA). Utbildningarna inleds hösten 2019.</p><h2>Ansökan till förberedande utbildningar efter grundläggande utbildning våren 2019</h2><p>I ansökan till förberedande utbildningar efter grundläggande utbildning <strong>21.5.–23.7.2019</strong> kan du söka till tionde klasser, utbildning som handleder för yrkesutbildning (VALMA) och utbildningar som förbereder invandrare och andra personer med ett främmande språk för gymnasium (LUVA). I vårens ansökan söker du till utbildningar som börjar på hösten 2019.</p><p>Läs mera om ansökan och antagning på <a href='http://www.studieinfo.fi' class='external' target='_blank'>www.studieinfo.fi</a></p><hr>"
  },
    "back-button" : {
      "fi" : "Takaisin",
      "sv" : "Back"
    }
  }
});
